Add region in provider.yaml
region is required resource type for kind Provider
of Alibaba Cloud or it will raise error message:
error: the server doesn't have a resource type "region"

Signed-off-by: zzxwill <zzxwill@gmail.com>
(cherry picked from commit e11286b7b1762ab2c1908556415cfc7bce8adc9f)