Add post-install,post-upgrade helm hook to install resource
Since CRDs are also part of the same helm chart, helm deployment
fails at validation with:
Error: validation failed: unable to recognize "": no matches for kind "ClusterStackInstall" in version "stacks.crossplane.io/v1alpha1"
Fix for this is adding crd-install hooks but kubebuilder does not have
built-in support for this. This commit adds post-install,post-upgrade
hooks to ClusterStackInstall resources, so that they will always
be installed after CRDs.

Signed-off-by: Hasan Turken <turkenh@gmail.com>